---
- name: Download v2ray installer
  become: true
  get_url:
    url: "{{v2ray_script_url}}"
    dest: /tmp/v2ray.sh
    mode: 755
    force: true

- name: Execute the v2ray.sh
  become: true
  command: /tmp/v2ray.sh

- name: Remove the v2ray.sh
  become: true
  file: 
    path: /tmp/v2ray.sh
    state: absent

- name: check if v2ray config exists
  local_action: stat path={{ v2ray_config_file_path }}
  register: v2ray_config
  tags:
    - v2ray
    - v2ray_config
    - debug

- name: v2ray config warning
  debug:
    msg: |
      v2ray config does not exists! please create your own config at
        {{ v2ray_config_file_path }}
  when: not v2ray_config.stat.exists
  tags:
    - v2ray
    - v2ray_config
    - debug

- name: sync v2ray config
  become: true
  copy:
    src: "{{ v2ray_config_file_path }}"
    dest: /usr/local/etc/v2ray/
  when: v2ray_config.stat.exists
  notify:
    - configtest
    - restart
  tags:
    - v2ray
    - v2ray_config

- name: enable v2ray
  become: true
  service:
    name: v2ray
    state: started
    enabled: true
  tags:
    - v2ray
    - v2ray_config
