---
- name: Download and unarchive nvidia_gpu_exporter into temporary location.
  unarchive:
    src: '{{ nvidia_gpu_exporter_download_url }}'
    dest: /tmp
    remote_src: true
    mode: 0755
  # when: >
  #   nvidia_gpu_exporter_version_check.stdout is not defined
  #   or nvidia_gpu_exporter_version not in nvidia_gpu_exporter_version_check.stdout
  register: nvidia_gpu_exporter_download_check

- name: Move nvidia_gpu_exporter binary into place.
  copy:
    src: '/tmp/nvidia_gpu_exporter'
    dest: '{{ nvidia_gpu_exporter_bin_path }}'
    mode: 0755
    remote_src: true
  notify: restart nvidia_gpu_exporter
  when: >
    nvidia_gpu_exporter_download_check is changed
  #   or nvidia_gpu_exporter_version_check.stdout | length == 0

- name: Copy the nvidia_gpu_exporter systemd unit file.
  template:
    src: nvidia_gpu_exporter.service.j2
    dest: /etc/systemd/system/nvidia_gpu_exporter.service
    mode: 0644
  become: true
  register: nvidia_gpu_exporter_service

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  become: true
  notify: restart nvidia_gpu_exporter
  when: nvidia_gpu_exporter_service is changed

- name: Ensure nvidia_gpu_exporter is running and enabled at boot.
  service:
    name: nvidia_gpu_exporter
    state: '{{ nvidia_gpu_exporter_state }}'
    enabled: '{{ nvidia_gpu_exporter_enabled }}'
  become: true
