---
name: Publish Collection

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Debug ref name
        run: echo "GITHUB_REF_NAME=${{ GITHUB_REF_NAME }}"
      
      - name: Debug ref
        run: echo "GITHUB_REF=${{ GITHUB_REF }}"

      - name: Publish Ansible Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          galaxy_version: "${{ GITHUB_REF_NAME }}"

      - name: Release
        uses: softprops/action-gh-release@v1
