---
name: Publish Collection

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish Ansible Collection
        uses: arillso/action.ansible.collection@1.3.0
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
          galaxy_version: "${{ env.GITHUB_REF_NAME }}"
